# -*- coding: utf-8 -*-
"""DNA: Counting DNA Nucleotides.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19nkXuXrixLksxX2f8YcdXbryxzVHt1i4

## DNA: [Counting DNA Nucleotides](https://rosalind.info/problems/dna/)
"""

def counter(string):
  """Solves https://rosalind.info/problems/dna/

  Given: A DNA string s of length at most 1000 nt.
  Return: Four integers (separated by spaces) counting the respective
  number of times that the symbols 'A', 'C', 'G', and 'T' occur in s, separated by spaces.
  """
  A_count = 0
  T_count = 0
  G_count = 0
  C_count = 0
  for i in string:
    if i == 'A':
      A_count += 1
    elif i == 'T':
      T_count += 1
    elif i == 'G':
      G_count += 1
    else:
      C_count += 1
  return f"{A_count} {C_count} {G_count} {T_count}"

help(counter)

SampleDataset = 'AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC'
counter(SampleDataset)

from google.colab import files

def string_from_uploaded_file():  
  uploaded = files.upload() # https://colab.research.google.com/notebooks/io.ipynb#scrollTo=BaCkyg5CV5jF
  for bytesObject in uploaded.values(): # https://www.w3schools.com/python/ref_dictionary_values.asp
    return bytesObject.decode('utf-8') # https://pythonexamples.org/python-bytes-to-string/#3
    
input_string = string_from_uploaded_file()
output_string = counter(input_string)
print(output_string)
with open('rosalind_dna_output.txt', 'w') as f:
  f.write(output_string)
files.download('rosalind_dna_output.txt') # https://colab.research.google.com/notebooks/io.ipynb#scrollTo=hauvGV4hV-Mh
