# -*- coding: utf-8 -*-
"""RNA: Transcribing DNA into RNA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19nkXuXrixLksxX2f8YcdXbryxzVHt1i4

## RNA: [Transcribing DNA into RNA](https://rosalind.info/problems/rna/)
"""

def dna_to_rna(string):
  """Solves https://rosalind.info/problems/rna/

  Given a DNA string t
 corresponding to a coding strand, its transcribed RNA string u
 is formed by replacing all occurrences of 'T' in t
 with 'U' in u.
  """
  wynik = string.replace('T', 'U')
  return wynik

help(dna_to_rna)

SampleDataset = 'GATGGAACTTGACTACGTAAATT'

dna_to_rna(SampleDataset)

from google.colab import files

def string_from_uploaded_file():  
  uploaded = files.upload() # https://colab.research.google.com/notebooks/io.ipynb#scrollTo=BaCkyg5CV5jF
  for bytesObject in uploaded.values(): # https://www.w3schools.com/python/ref_dictionary_values.asp
    return bytesObject.decode('utf-8') # https://pythonexamples.org/python-bytes-to-string/#3
    
input_string = string_from_uploaded_file()
output_string = dna_to_rna(input_string)
print(output_string)
with open('rosalind_rna_output.txt', 'w') as f:
  f.write(output_string)
files.download('rosalind_rna_output.txt') # https://colab.research.google.com/notebooks/io.ipynb#scrollTo=hauvGV4hV-Mh