# -*- coding: utf-8 -*-
"""SUBS: Finding a Motif in DNA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19nkXuXrixLksxX2f8YcdXbryxzVHt1i4

## SUBS: [Finding a Motif in DNA](https://rosalind.info/problems/subs/)
"""

def Motif(input_string):
    """ Solve https://rosalind.info/problems/subs/

    Given: Two DNA strings s and t (each of length at most 1 kbp) on separate lines.
    Return: All locations of t as a substring of s. """
    
    # split input string into two sequences
    string1, string2 = input_string.strip().split("\n")
    
    positions = []
    for i in range(len(string1) - len(string2) + 1):
        if string1[i:i+len(string2)] == string2:
            positions.append(str(i+1))
    return ' '.join(positions)

sample_data = 'GATATATGCATATACTT\nATAT'
Motif(sample_data) == '2 4 10'

from google.colab import files

def string_from_uploaded_file():  
  uploaded = files.upload() # https://colab.research.google.com/notebooks/io.ipynb#scrollTo=BaCkyg5CV5jF
  for bytesObject in uploaded.values(): # https://www.w3schools.com/python/ref_dictionary_values.asp
    return bytesObject.decode('utf-8') # https://pythonexamples.org/python-bytes-to-string/#3
    
input_string = string_from_uploaded_file()
output_string = Motif(input_string)
print(output_string)
with open('rosalind_subs_output.txt', 'w') as f:
  f.write(output_string)
files.download('rosalind_subs_output.txt') # https://colab.research.google.com/notebooks/io.ipynb#scrollTo=hauvGV4hV-Mh